# Continous Integration setup for SU2.
# Tests on the develop and master branch in both serial and parallel.

language: cpp

compiler:
    - g++

notifications:
    email:
        - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2

env:
    # Set the build matrix
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./configure CXXFLAGS=-O3 --prefix=/usr/local"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        - CONFIGURE_COMMAND="./configure --enable-mpi --with-cc=`which mpicc` --with-cxx=`which mpicxx` CXXFLAGS=-O3"
          TEST_SCRIPT=parallel_regression.py

install:
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    # Add environmental variables according to the configure step
    # Can I add this after the install.
    - make -j 8
    - sudo make install
    - export SU2_RUN="/usr/local/bin"
    # Find out what SU2_HOME is used for.
    #- export SU2_HOME="/home/travis/build/su2code/SU2"
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone https://github.com/su2code/TestCases.git
    - cd TestCases/
    - git checkout feature_TravisCI

script:
    # run the tests
    python $TEST_SCRIPT

